### ISSUE TITLE
Service not found (symfony)

### ISSUE THREAD

**Issue by GeneralCrime** [GeneralCrime/apf-umgt-doctrine#1]
The "GeneralCrime\Apf\Umgt\Doctrine\Repository\UserRepository" entity repository implements 
"Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure 
the service exists and is tagged with "doctrine.repository_service".

doctrine.yaml
```
mappings:
          Umgt:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/vendor/generalcrime/apf-umgt-doctrine/src/Entity'
            prefix: 'GeneralCrime\Apf\Umgt\Doctrine\Entity'
            alias: Umgt
```
